source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target '吃货美食' do
pod 'AFNetworking', '~> 3.0'
end
pod 'MJRefresh'

pod 'MJExtension'
platform :ios, '7.0'
pod 'SDWebImage', '~>3.8'

pod 'MBProgressHUD', '~> 0.9.2'

pod 'FMDB'
# pod 'FMDB/FTS'   # FMDB with FTS
# pod 'FMDB/standalone'   # FMDB with latest SQLite amalgamation source
# pod 'FMDB/standalone/FTS'   # FMDB with latest SQLite amalgamation source and FTS
# pod 'FMDB/SQLCipher'   # FMDB with SQLCipher

